# Generated by Django 2.1.7 on 2019-10-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roll',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
