# Generated by Django 2.1.7 on 2019-10-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_roll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursevideo',
            old_name='videofile',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='coursevideo',
            old_name='name',
            new_name='title',
        ),
    ]
