# Generated by Django 2.1.7 on 2019-10-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191019_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_approved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='miscnote',
            name='is_approved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='is_approved',
            field=models.IntegerField(default=0),
        ),
    ]
